// export const eventMeta = {
//   title: "Summit\nSpeakers",
//   department: "Creative & Innovation Track",
//   date: "November 2025",
//   url: "www.reallygreat.site",
// };

// export const speakers = [
//   {
//     id: 1,
//     role: "Keynote Speaker",
//     name: "Arjun Mehta",
//     topic: "The Future of Human-AI Collaboration",
//     age: "34 YO",
//     bg: "teal",
//     // Using a DiceBear avatar URL (SVG-based, no copyright issues)
//     image: "https://api.dicebear.com/7.x/personas/svg?seed=Arjun&backgroundColor=transparent&size=200",
//   },
//   {
//     id: 2,
//     role: "Workshop Lead",
//     name: "Sofia Reyes",
//     topic: "Designing for Emerging Markets",
//     age: "29 YO",
//     bg: "amber",
//     image: "https://api.dicebear.com/7.x/personas/svg?seed=Sofia&backgroundColor=transparent&size=200",
//   },
//   {
//     id: 3,
//     role: "Panel Moderator",
//     name: "James Okoye",
//     topic: "Ethics in Product Development",
//     age: "41 YO",
//     bg: "slate",
//     image: "https://api.dicebear.com/7.x/personas/svg?seed=James&backgroundColor=transparent&size=200",
//   },
//   {
//     id: 4,
//     role: "Tech Director",
//     name: "Priya Nair",
//     topic: "Scaling Startups in 2025",
//     age: "36 YO",
//     bg: "dark",
//     image: "https://api.dicebear.com/7.x/personas/svg?seed=Priya&backgroundColor=transparent&size=200",
//   },
//   {
//     id: 5,
//     role: "Creative Lead",
//     name: "Marco Deluca",
//     topic: "Brand Identity at Scale",
//     age: "44 YO",
//     bg: "ivory",
//     image: "https://api.dicebear.com/7.x/personas/svg?seed=Marco&backgroundColor=transparent&size=200",
//   },
//   {
//     id: 6,
//     role: "UX Strategist",
//     name: "Lena Vogel",
//     topic: "Invisible Interfaces",
//     age: "31 YO",
//     bg: "rose",
//     image: "https://api.dicebear.com/7.x/personas/svg?seed=Lena&backgroundColor=transparent&size=200",
//   },
// ];
/* ─── SPEAKER CATEGORIES ─────────────────────── */
export const speakerCategories = [
  { id: "all", label: "All Speakers" },
  { id: "women-leadership", label: "Women & Leadership" },
  { id: "ai-stem", label: "AI & STEM" },
  { id: "business", label: "Business" },
  { id: "wellness", label: "Wellness" },
];

/* ─── SPEAKERS DATA ──────────────────────────── */
export const speakers = [
  /* ── WOMEN & LEADERSHIP ───────────────────── */
  {
    id: 1,
    name: "Aisha Nkemdirim",
    role: "CEO, FutureForward Africa",
    topic: "Redefining Leadership in the Global South",
    category: "women-leadership",
    country: "Nigeria",
    conference: "WE Summit Mumbai",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 2,
    name: "Priya Chandrasekaran",
    role: "Managing Director, Apex Ventures",
    topic: "Breaking the Bamboo Ceiling",
    category: "women-leadership",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "rose",
    image:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 3,
    name: "Yuki Tanaka",
    role: "Co-Founder, NovaTech Japan",
    topic: "Women Who Build: Tech Startups in Asia",
    category: "women-leadership",
    country: "Japan",
    conference: "WE Summit Tokyo",
    bg: "amber",
    image:
      "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 4,
    name: "Fatima Al-Rashidi",
    role: "Deputy Minister of Innovation",
    topic: "Policy as a Tool for Gender Equity",
    category: "women-leadership",
    country: "UAE",
    conference: "WE Summit Dubai",
    bg: "slate",
    image:
      "https://images.unsplash.com/photo-1614644147798-f8c0fc9da7f6?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 5,
    name: "Grace Osei-Bonsu",
    role: "Founder, She Leads Africa",
    topic: "Community Capital: Funding Women-Led Ventures",
    category: "women-leadership",
    country: "Ghana",
    conference: "WE Summit Mumbai",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 6,
    name: "Sofia Herrera",
    role: "President, Latam Growth Partners",
    topic: "Cross-Border Leadership in Emerging Markets",
    category: "women-leadership",
    country: "Colombia",
    conference: "WE Summit Singapore",
    bg: "ivory",
    image:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 7,
    name: "Mei-Ling Chen",
    role: "Chief People Officer, TechGiant Asia",
    topic: "Building Cultures of Belonging at Scale",
    category: "women-leadership",
    country: "Taiwan",
    conference: "WE Summit Singapore",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=500&fit=crop&crop=face",
  },

  {
    id: 9,
    name: "Divya Menon",
    role: "Global Ambassador, UN Women",
    topic: "Financing Gender Equality by 2030",
    category: "women-leadership",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "amber",
    image:
      "https://images.unsplash.com/photo-1504703395950-b89145a5425b?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 10,
    name: "Miriam Okonkwo",
    role: "Founder, Africa Tech Women",
    topic: "Funding Female Founders in Africa",
    category: "women-leadership",
    country: "Nigeria",
    conference: "WE Summit Dubai",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1589156280159-27698a70f29e?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 11,
    name: "Dr. Leila Ahmadi",
    role: "Women's Rights Lawyer & Activist",
    topic: "Legal Empowerment as Economic Empowerment",
    category: "women-leadership",
    country: "Iran",
    conference: "WE Summit Dubai",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=500&fit=crop&crop=face",
  },

  /* ── AI & STEM ─────────────────────────────── */
  {
    id: 12,
    name: "Dr. Rohan Kapoor",
    role: "Lead AI Researcher, DeepMind",
    topic: "Large Language Models: Beyond the Hype",
    category: "ai-stem",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 13,
    name: "Dr. Lena Fischer",
    role: "Director, Berlin AI Institute",
    topic: "Responsible AI: Building Ethical Frameworks",
    category: "ai-stem",
    country: "Germany",
    conference: "WE Summit Singapore",
    bg: "slate",
    image:
      "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 14,
    name: "James Okafor",
    role: "CTO, Quantum Labs",
    topic: "Quantum Computing: Practical Applications in 2026",
    category: "ai-stem",
    country: "Nigeria",
    conference: "WE Summit Dubai",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 15,
    name: "Aiko Watanabe",
    role: "Principal Engineer, Sony AI",
    topic: "Generative AI in Creative Industries",
    category: "ai-stem",
    country: "Japan",
    conference: "WE Summit Tokyo",
    bg: "amber",
    image:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 16,
    name: "Dr. Marcus Webb",
    role: "Professor of Robotics, MIT",
    topic: "The Next Decade of Human-Robot Collaboration",
    category: "ai-stem",
    country: "USA",
    conference: "WE Summit Singapore",
    bg: "ivory",
    image:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 17,
    name: "Neha Sharma",
    role: "VP of Engineering, Infosys",
    topic: "Women in STEM: Closing the Pipeline Gap",
    category: "ai-stem",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "rose",
    image:
      "https://images.unsplash.com/photo-1541823709867-1b206113eafd?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 18,
    name: "Tariq Al-Amin",
    role: "Head of AI Strategy, Google MENA",
    topic: "AI Adoption Across Developing Economies",
    category: "ai-stem",
    country: "Jordan",
    conference: "WE Summit Dubai",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 19,
    name: "Dr. Zoe Papadopoulos",
    role: "Climate Tech Scientist, Oxford",
    topic: "AI-Powered Climate Modelling",
    category: "ai-stem",
    country: "Greece",
    conference: "WE Summit Singapore",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 20,
    name: "Carlos Mendoza",
    role: "Founder, NeuralPath Labs",
    topic: "Brain-Computer Interfaces: Where We Are Now",
    category: "ai-stem",
    country: "Mexico",
    conference: "WE Summit Tokyo",
    bg: "amber",
    image:
      "https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 21,
    name: "Ingrid Bjornsson",
    role: "Chief Data Scientist, Spotify",
    topic: "Personalization at Billion-User Scale",
    category: "ai-stem",
    country: "Sweden",
    conference: "WE Summit Singapore",
    bg: "slate",
    image:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 22,
    name: "Ahmad Karimi",
    role: "Blockchain Architect, Binance",
    topic: "Web3 Infrastructure in the Real World",
    category: "ai-stem",
    country: "Iran",
    conference: "WE Summit Dubai",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 23,
    name: "Dr. Pita Havili",
    role: "Oceanographer & Climate Activist",
    topic: "Rising Tides: Science, Policy and Survival",
    category: "ai-stem",
    country: "Fiji",
    conference: "WE Summit Singapore",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 24,
    name: "Nia Campbell",
    role: "Tech Policy Advisor, World Bank",
    topic: "Governance Frameworks for AI in Government",
    category: "ai-stem",
    country: "USA",
    conference: "WE Summit Dubai",
    bg: "rose",
    image:
      "https://images.unsplash.com/photo-1601412436009-d964bd02edbc?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 25,
    name: "Isabela Carvalho",
    role: "Founder, BioHack Brazil",
    topic: "Biotech Startups: From Lab to Market",
    category: "ai-stem",
    country: "Brazil",
    conference: "WE Summit Singapore",
    bg: "amber",
    image:
      "https://images.unsplash.com/photo-1558203728-00f45181dd84?w=400&h=500&fit=crop&crop=face",
  },

  /* ── BUSINESS ──────────────────────────────── */
  {
    id: 26,
    name: "Ravi Subramaniam",
    role: "Chairman, Subramaniam Group",
    topic: "Family Enterprises in the Digital Age",
    category: "business",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 27,
    name: "Elena Volkov",
    role: "Managing Partner, Horizon Capital",
    topic: "Venture Capital in Frontier Markets",
    category: "business",
    country: "Russia",
    conference: "WE Summit Dubai",
    bg: "ivory",
    image:
      "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 28,
    name: "David Asante",
    role: "CEO, Pan-African Trade Alliance",
    topic: "AfCFTA: Africa's Trillion-Dollar Opportunity",
    category: "business",
    country: "Ghana",
    conference: "WE Summit Mumbai",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 29,
    name: "Nadia Petrov",
    role: "CFO, EastWest Financial",
    topic: "Navigating Currency Risk in 2026",
    category: "business",
    country: "Bulgaria",
    conference: "WE Summit Singapore",
    bg: "rose",
    image:
      "https://images.unsplash.com/photo-1614283233556-f35b0c801ef1?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 30,
    name: "Ben Hartley",
    role: "Founder, Decarbonize Inc.",
    topic: "Green Business: Profit and Planet Aligned",
    category: "business",
    country: "Australia",
    conference: "WE Summit Singapore",
    bg: "amber",
    image:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 31,
    name: "Ximena Torres",
    role: "Head of Strategy, BBVA",
    topic: "Open Banking and the Future of Finance",
    category: "business",
    country: "Spain",
    conference: "WE Summit Dubai",
    bg: "slate",
    image:
      "https://images.unsplash.com/photo-1548142813-c348350df52b?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 32,
    name: "Jin-Woo Park",
    role: "VP of Global Markets, Samsung",
    topic: "Hardware Renaissance: From Chips to Ecosystems",
    category: "business",
    country: "South Korea",
    conference: "WE Summit Tokyo",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1530268729831-4b0b9e170218?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 33,
    name: "Amira Hassan",
    role: "Founder, Nomad Brands",
    topic: "Building Global Consumer Brands from the Middle East",
    category: "business",
    country: "Egypt",
    conference: "WE Summit Dubai",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 34,
    name: "Oliver Huang",
    role: "COO, Alibaba International",
    topic: "Cross-Border E-Commerce: Lessons from the East",
    category: "business",
    country: "China",
    conference: "WE Summit Singapore",
    bg: "ivory",
    image:
      "https://images.unsplash.com/photo-1463453091185-61582044d556?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 35,
    name: "Funmilayo Adeyemi",
    role: "CEO, Lagos Fintech Hub",
    topic: "Mobile Money: Banking Africa's Unbanked",
    category: "business",
    country: "Nigeria",
    conference: "WE Summit Mumbai",
    bg: "rose",
    image:
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 36,
    name: "Matthias Richter",
    role: "Director, European Startup Fund",
    topic: "Deep Tech Investing: A European Perspective",
    category: "business",
    country: "Germany",
    conference: "WE Summit Singapore",
    bg: "amber",
    image:
      "https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 37,
    name: "Kavya Reddy",
    role: "Founder & CEO, EduTech India",
    topic: "EdTech at 100 Million Users: Scaling with Purpose",
    category: "business",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "slate",
    image:
      "https://images.unsplash.com/photo-1590086782792-42dd2350140d?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 38,
    name: "Linh Nguyen",
    role: "Head of Product, Sea Group",
    topic: "Southeast Asia's Superapp Revolution",
    category: "business",
    country: "Vietnam",
    conference: "WE Summit Singapore",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 39,
    name: "Samuel Nwosu",
    role: "Director, African Climate Fund",
    topic: "Climate Finance for Developing Nations",
    category: "business",
    country: "Nigeria",
    conference: "WE Summit Dubai",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 40,
    name: "Chloe Beaumont",
    role: "Creative Director, LVMH",
    topic: "Luxury in the Age of Conscious Consumers",
    category: "business",
    country: "France",
    conference: "WE Summit Tokyo",
    bg: "ivory",
    image:
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 41,
    name: "Takeshi Yamamoto",
    role: "SVP, Softbank Vision Fund",
    topic: "The Next 100 Billion Dollar Companies",
    category: "business",
    country: "Japan",
    conference: "WE Summit Tokyo",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1508341591423-4347099e1f19?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 42,
    name: "Raj Pillai",
    role: "Head of Innovation, Tata Group",
    topic: "Corporate Innovation at a 150-Year-Old Company",
    category: "business",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "rose",
    image:
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 43,
    name: "Kwame Asiedu",
    role: "Chairman, West Africa VC Council",
    topic: "Patient Capital: Long-Term Investing in Africa",
    category: "business",
    country: "Ghana",
    conference: "WE Summit Mumbai",
    bg: "amber",
    image:
      "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 44,
    name: "Tobias Lindgren",
    role: "Chief Sustainability Officer, IKEA",
    topic: "Circular Economy: Scaling What Works",
    category: "business",
    country: "Sweden",
    conference: "WE Summit Singapore",
    bg: "slate",
    image:
      "https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?w=400&h=500&fit=crop&crop=face",
  },

  /* ── WELLNESS ───────────────────────────────── */
  {
    id: 45,
    name: "Dr. Ananya Krishnan",
    role: "Psychiatrist & Author",
    topic: "Mental Health in High-Performance Cultures",
    category: "wellness",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 46,
    name: "Kenji Mori",
    role: "Longevity Researcher, Kyoto University",
    topic: "The Science of Living to 120",
    category: "wellness",
    country: "Japan",
    conference: "WE Summit Tokyo",
    bg: "ivory",
    image:
      "https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 47,
    name: "Binta Diagne",
    role: "Holistic Wellness Coach",
    topic: "Ubuntu and Collective Healing",
    category: "wellness",
    country: "Senegal",
    conference: "WE Summit Dubai",
    bg: "rose",
    image:
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 48,
    name: "Dr. Arjun Nair",
    role: "Ayurvedic Medicine Practitioner",
    topic: "Ancient Wisdom for Modern Burnout",
    category: "wellness",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "amber",
    image:
      "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 49,
    name: "Hana Kovář",
    role: "Neuroscience & Mindfulness Expert",
    topic: "Rewiring the Stressed Brain",
    category: "wellness",
    country: "Czech Republic",
    conference: "WE Summit Singapore",
    bg: "slate",
    image:
      "https://images.unsplash.com/photo-1532074205216-d0e1f4b87368?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 50,
    name: "Taraji Williams",
    role: "Founder, Black Girl Wellness",
    topic: "Radical Rest as Resistance",
    category: "wellness",
    country: "USA",
    conference: "WE Summit Mumbai",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 51,
    name: "Dr. Rafael Souza",
    role: "Sports Medicine Physician",
    topic: "Optimizing Performance Without Burnout",
    category: "wellness",
    country: "Brazil",
    conference: "WE Summit Dubai",
    bg: "teal",
    image:
      "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 52,
    name: "Sunita Patel",
    role: "Yoga & Breathwork Teacher",
    topic: "Breath: The Original Biohack",
    category: "wellness",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "rose",
    image:
      "https://images.unsplash.com/photo-1545912452-8aea7e25a3d3?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 53,
    name: "Dr. Sanjay Iyer",
    role: "Cardiologist & Wellness Author",
    topic: "Heart Health for High Achievers",
    category: "wellness",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "amber",
    image:
      "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 54,
    name: "Dr. Asha Kumari",
    role: "Neuroscientist, NIMHANS",
    topic: "The Neuroscience of High Performance",
    category: "wellness",
    country: "India",
    conference: "WE Summit Mumbai",
    bg: "ivory",
    image:
      "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400&h=500&fit=crop&crop=face",
  },
  {
    id: 55,
    name: "Sara Kim",
    role: "Olympic Athlete & Coach",
    topic: "Peak Performance: Lessons from Elite Sport",
    category: "wellness",
    country: "South Korea",
    conference: "WE Summit Tokyo",
    bg: "dark",
    image:
      "https://images.unsplash.com/photo-1601412436009-d964bd02edbc?w=400&h=500&fit=crop&crop=face",
  },
];

/* ─── HELPERS ────────────────────────────────── */
export const getSpeakersByCategory = (category) =>
  category === "all"
    ? speakers
    : speakers.filter((s) => s.category === category);

export const getSpeakerById = (id) => speakers.find((s) => s.id === Number(id));

export const allConferences = [...new Set(speakers.map((s) => s.conference))];
