import { eventImages } from "./eventsImages.jsx";

const conferenceSeed = [
  {
    id: 1,
    title: "Global Women Leadership & Mental Resilience Signature Conference",
    date: "August 08-09, 2026",
    location: "Auckland, New Zealand",
    city: "Auckland",
    country: "New Zealand",
    category: "women-leadership",
    imageKey: "home_img_1",
    description:
      "The Global Women Leadership & Mental Resilience Signature Conference is a dynamic international platform designed to empower women leaders to navigate today's fast-paced and demanding world with strength, clarity, and confidence. Bringing together global leaders, entrepreneurs, professionals, and changemakers, the conference focuses on the powerful connection between effective leadership and mental resilience.\n\nThrough inspiring keynote sessions, expert-led panels, and interactive discussions, the event addresses key areas such as emotional intelligence, stress management, burnout prevention, and building resilience in leadership. Participants will gain practical insights, tools, and strategies to enhance both their personal wellbeing and professional performance.\n\nThe conference also fosters meaningful networking and collaboration, creating a supportive environment where ideas are shared, experiences are valued, and new opportunities are formed. It is an ideal space for women to strengthen their leadership capabilities, expand their global presence, and contribute to a more resilient, inclusive, and future-ready leadership landscape.",
    themes: [
      "Women's Leadership & Mental Resilience",
      "Emotional Intelligence & Adaptive Leadership",
      "Mental Health Challenges in Leadership",
      "Mindfulness & Self-Awareness in Leadership",
      "Stress Management & Burnout Prevention",
      "Building Psychological Resilience in Women Leaders",
      "Overcoming Anxiety, Self-Doubt & Imposter Syndrome",
      "Trauma-Informed Leadership & Healing Practices",
      "Psychological Safety & Trust in Teams",
      "Purpose-Driven Leadership & Inner Strength",
      "Work-Life Balance & Sustainable Success",
      "Self-Care as a Leadership Strategy",
      "Holistic Wellness: Mind, Body & Performance",
      "Leadership in Crisis & Uncertainty",
      "Inclusive Leadership & Workplace Wellbeing",
      "Neuroscience of Resilience & Decision-Making",
      "Coaching, Mentorship & Leadership Development",
      "High-Performance Leadership with Mental Wellness",
      "Diversity, Equity & Inclusion in Leadership",
      "Future of Women Leadership & Global Impact",
    ],
    fullDescription:
      "Theme: Resilient Minds, Empowered Leaders: Shaping the Future of Women's Leadership",
  },
  {
    id: 2,
    title: "Signature Global Legacy Conference",
    date: "August 08-09, 2026",
    location: "Auckland, New Zealand",
    city: "Auckland",
    country: "New Zealand",
    category: "business",
    imageKey: "home_img_2",
    description:
      "The Signature Global Legacy Conference is a premier international platform dedicated to inspiring leaders, innovators, and changemakers to build meaningful and lasting impact. This conference brings together global professionals, entrepreneurs, executives, and thought leaders to explore the principles of legacy-driven leadership, innovation, and sustainable growth in an ever-evolving world.\n\nThrough impactful keynote sessions, expert-led panels, and interactive discussions, the conference focuses on shaping visionary leaders who not only succeed in the present but also create value for future generations. Participants will gain insights into strategic thinking, ethical leadership, personal branding, and long-term impact creation.\n\nDesigned to foster collaboration and global connections, the conference provides a unique space to exchange ideas, share experiences, and build partnerships that drive progress. It empowers attendees to define their purpose, strengthen their leadership journey, and leave a lasting legacy that contributes to a more innovative, inclusive, and future-ready world.",
    themes: [
      "Legacy Leadership & Long-Term Impact",
      "Visionary Leadership & Future Thinking",
      "Purpose-Driven Leadership & Value Creation",
      "Innovation & Sustainable Growth",
      "Ethical Leadership & Governance",
      "Women in Leadership & Global Influence",
      "Entrepreneurship & Legacy Building",
      "Strategic Thinking & Decision-Making",
      "Leadership in a Changing Global Landscape",
      "Mentorship, Succession & Leadership Development",
      "Personal Branding & Thought Leadership",
      "Financial Growth & Wealth Legacy",
      "Social Impact & Community Leadership",
      "Diversity, Equity & Inclusive Leadership",
      "Resilience & Adaptability in Leadership",
      "Digital Transformation & Future Leadership",
      "Building High-Performance Organizations",
      "Collaboration, Partnerships & Global Networking",
      "Leadership Communication & Influence",
      "Creating a Future-Ready Leadership Ecosystem",
    ],
    fullDescription:
      "Theme: Building Lasting Impact: Leadership, Innovation, and Legacy for the Future",
  },
  {
    id: 3,
    title: "Thrive & Lead: Women's Mental Health Signature Conference",
    date: "September 08-09, 2026",
    location: "Tokyo, Japan",
    city: "Tokyo",
    country: "Japan",
    category: "wellness",
    imageKey: "home_img_3",
    description:
      "The Thrive & Lead: Women's Mental Health Signature Conference is a transformative global platform dedicated to empowering women to prioritize their mental wellbeing while excelling in leadership. Bringing together women leaders, professionals, entrepreneurs, and mental health advocates, the conference focuses on the critical connection between mental health and sustainable leadership success.\n\nThrough inspiring keynote sessions, expert-led panels, and interactive discussions, the event explores key topics such as emotional intelligence, stress management, burnout prevention, self-care, and resilience. Attendees will gain practical tools and strategies to strengthen their mental health, enhance their leadership capabilities, and navigate personal and professional challenges with confidence.\n\nThe conference also fosters a supportive and inclusive environment for meaningful networking, knowledge sharing, and collaboration. It empowers women to lead with clarity, balance, and purpose while contributing to healthier workplaces and a more resilient global community.",
    themes: [
      "Women's Mental Health & Leadership",
      "Emotional Intelligence & Self-Awareness",
      "Stress Management & Burnout Prevention",
      "Building Mental Resilience in Women Leaders",
      "Mindfulness & Wellbeing in Leadership",
      "Overcoming Anxiety, Self-Doubt & Imposter Syndrome",
      "Work-Life Balance & Sustainable Success",
      "Self-Care as a Leadership Strategy",
      "Psychological Safety & Supportive Work Environments",
      "Trauma-Informed Leadership & Healing Approaches",
      "Holistic Wellness: Mind, Body & Performance",
      "Leadership Confidence & Personal Growth",
      "Mental Health in High-Performance Environments",
      "Coaching & Mentorship for Wellbeing",
      "Neuroscience of Mental Health & Leadership",
      "Inclusive Leadership & Workplace Wellbeing",
      "Resilience in Times of Change & Crisis",
      "Purpose-Driven Leadership & Inner Alignment",
      "Energy Management & Productivity",
      "Creating a Culture of Wellbeing in Organizations",
    ],
    fullDescription:
      "Theme: Thriving Minds, Empowered Leaders: Advancing Women's Mental Health and Leadership Excellence",
  },
  {
    id: 4,
    title: "Signature Global Future Leaders Conference",
    date: "September 08-09, 2026",
    location: "Tokyo, Japan",
    city: "Tokyo",
    country: "Japan",
    category: "business",
    imageKey: "home_img_4",
    description:
      "The Signature Global Future Leaders Conference is a dynamic international platform designed to inspire and equip the next generation of leaders with the skills, vision, and mindset needed to succeed in a rapidly evolving world. Bringing together emerging leaders, young professionals, entrepreneurs, and industry experts, the conference focuses on developing future-ready leadership capabilities and fostering innovation.\n\nThrough engaging keynote sessions, expert-led panels, and interactive workshops, the event explores essential topics such as strategic thinking, digital transformation, leadership communication, entrepreneurship, and global collaboration. Attendees will gain practical insights, valuable tools, and real-world perspectives to enhance their personal and professional growth.\n\nThe conference also provides a powerful networking environment, connecting participants with global mentors, industry leaders, and like-minded peers. It empowers individuals to build confidence, expand their vision, and step into leadership roles that drive meaningful impact and shape the future.",
    themes: [
      "Future Leadership Skills & Competencies",
      "Visionary Leadership & Strategic Thinking",
      "Innovation & Emerging Technologies",
      "Digital Transformation & AI in Leadership",
      "Leadership Communication & Influence",
      "Emotional Intelligence & Adaptive Leadership",
      "Entrepreneurship & Startup Leadership",
      "Personal Branding & Leadership Identity",
      "Youth Leadership & Career Development",
      "Diversity, Equity & Inclusive Leadership",
      "Global Leadership & Cross-Cultural Competence",
      "Resilience & Change Management",
      "Decision-Making & Problem-Solving Skills",
      "Mentorship, Coaching & Leadership Growth",
      "Sustainable Leadership & Social Impact",
      "Networking & Collaborative Leadership",
      "Ethics & Values-Based Leadership",
      "Women & Next-Gen Leadership",
      "High-Performance Leadership Strategies",
      "Building Future-Ready Organizations",
    ],
    fullDescription:
      "Theme: Empowering Tomorrow's Leaders: Innovation, Vision, and Global Impact",
  },
  {
    id: 5,
    title:
      "Women's Leadership and Psychological Wellbeing Signature Global Conference",
    date: "September 08-09, 2026",
    location: "Tokyo, Japan",
    city: "Tokyo",
    country: "Japan",
    category: "women-leadership",
    imageKey: "home_img_5",
    description:
      "The Women's Leadership and Psychological Wellbeing Signature Global Conference is a premier international platform dedicated to empowering women leaders to thrive both personally and professionally. This conference brings together global leaders, professionals, mental health experts, and changemakers to explore the vital connection between effective leadership and psychological wellbeing.\n\nThrough insightful keynote sessions, expert-led panels, and interactive discussions, the event focuses on key areas such as emotional intelligence, stress management, burnout prevention, resilience, and creating supportive work environments. Participants will gain practical strategies to enhance their mental wellbeing while strengthening their leadership capabilities.\n\nThe conference fosters a collaborative and inclusive environment where attendees can share experiences, exchange ideas, and build meaningful global connections. It is designed to support women in leading with confidence, balance, and purpose, while contributing to healthier workplaces and a more resilient and empowered leadership community.",
    themes: [
      "Women's Leadership & Psychological Wellbeing",
      "Emotional Intelligence & Self-Awareness",
      "Mental Health in Leadership",
      "Mindful Leadership & Cognitive Wellbeing",
      "Stress Management & Burnout Prevention",
      "Building Psychological Resilience in Women Leaders",
      "Overcoming Anxiety, Self-Doubt & Imposter Syndrome",
      "Trauma-Informed Leadership & Healing Practices",
      "Psychological Safety & Trust in Teams",
      "Work-Life Balance & Sustainable Leadership",
      "Self-Care as a Leadership Strategy",
      "Holistic Wellness: Mind, Body & Performance",
      "Leadership Confidence & Personal Growth",
      "Neuroscience of Mental Health & Leadership",
      "Inclusive Leadership & Workplace Wellbeing",
      "Resilience in Times of Change & Crisis",
      "Coaching, Mentorship & Leadership Development",
      "Creating Healthy & Supportive Work Cultures",
      "Purpose-Driven Leadership & Inner Alignment",
      "Future of Women's Leadership & Wellbeing",
    ],
    fullDescription:
      "Theme: Empowered Minds, Transformative Leadership: Advancing Women's Wellbeing and Impact",
  },
  {
    id: 6,
    title: "She Leads & Heals Signature Global Conference",
    date: "October 08-09, 2026",
    location: "Melbourne, Australia",
    city: "Melbourne",
    country: "Australia",
    category: "women-leadership",
    imageKey: "home_img_6",
    description:
      "The She Leads & Heals Signature Global Conference is a transformative international platform dedicated to empowering women to lead with strength while prioritizing healing and holistic wellbeing. Bringing together women leaders, professionals, entrepreneurs, coaches, and changemakers from around the world, the conference explores the powerful connection between leadership, emotional healing, and personal growth.\n\nThrough inspiring keynote sessions, expert-led panels, and interactive discussions, the event focuses on key areas such as mental wellness, emotional intelligence, resilience, self-awareness, and healing-centered leadership. Attendees will gain practical tools and strategies to overcome challenges, restore balance, and lead with clarity, compassion, and confidence.\n\nThe conference fosters a supportive and inclusive environment for meaningful networking, knowledge sharing, and collaboration. It empowers participants to grow both personally and professionally, while contributing to a more compassionate, resilient, and future-ready leadership landscape.",
    themes: [
      "Women's Leadership & Healing-Centered Approaches",
      "Emotional Intelligence & Compassionate Leadership",
      "Mental Health & Wellbeing in Leadership",
      "Mindfulness, Meditation & Inner Healing",
      "Trauma-Informed Leadership & Recovery",
      "Stress Management & Burnout Prevention",
      "Building Resilience Through Healing Practices",
      "Self-Awareness & Personal Transformation",
      "Work-Life Balance & Sustainable Leadership",
      "Self-Care as a Leadership Strategy",
      "Psychological Safety & Supportive Work Cultures",
      "Holistic Wellness: Mind, Body & Spirit",
      "Overcoming Anxiety, Self-Doubt & Emotional Barriers",
      "Purpose-Driven Leadership & Inner Alignment",
      "Coaching & Mentorship for Healing & Growth",
      "Energy Healing & Performance Optimization",
      "Leadership Confidence & Emotional Strength",
      "Creating Inclusive & Compassionate Organizations",
      "Healing Through Connection & Community Building",
      "Transformational Leadership & Global Impact",
    ],
    fullDescription:
      "Theme: Healing Leaders, Empowered Futures: Integrating Wellness, Purpose, and Impact",
  },
  {
    id: 7,
    title: "Empowered Women, Healthy Minds Signature Global Conference",
    date: "October 08-09, 2026",
    location: "Melbourne, Australia",
    city: "Melbourne",
    country: "Australia",
    category: "wellness",
    imageKey: "home_img_7",
    description:
      "The Empowered Women, Healthy Minds Signature Global Conference is a premier international platform dedicated to advancing women's leadership through the lens of mental wellbeing and holistic growth. Bringing together women leaders, professionals, entrepreneurs, and mental health advocates from around the world, the conference highlights the vital connection between a healthy mind and effective, sustainable leadership.\n\nThrough inspiring keynote sessions, expert-led panels, and interactive discussions, the event explores key topics such as emotional intelligence, stress management, resilience, self-care, and creating mentally healthy workplaces. Attendees will gain practical tools, valuable insights, and real-world strategies to enhance both their personal wellbeing and professional performance.\n\nThe conference also fosters meaningful networking and collaboration, creating a supportive environment where participants can share experiences, exchange ideas, and build lasting connections. It empowers women to lead with confidence, balance, and purpose while contributing to a more inclusive, resilient, and future-ready global community.",
    themes: [
      "Women's Leadership & Mental Wellbeing",
      "Emotional Intelligence & Self-Awareness",
      "Mental Health in Leadership Roles",
      "Mindfulness & Cognitive Wellbeing",
      "Stress Management & Burnout Prevention",
      "Building Mental Resilience in Women",
      "Overcoming Anxiety, Self-Doubt & Imposter Syndrome",
      "Psychological Safety & Trust in Teams",
      "Work-Life Balance & Sustainable Leadership",
      "Self-Care as a Leadership Strategy",
      "Holistic Wellness: Mind, Body & Performance",
      "Trauma-Informed Leadership & Healing Practices",
      "Leadership Confidence & Personal Growth",
      "Neuroscience of Mental Health & Decision-Making",
      "Inclusive Leadership & Workplace Wellbeing",
      "Coaching & Mentorship for Wellbeing",
      "Energy Management & Productivity",
      "Creating Healthy & Supportive Work Cultures",
      "Purpose-Driven Leadership & Inner Alignment",
      "Future of Women's Leadership & Mental Health",
    ],
    fullDescription:
      "Theme: Empowered Women, Healthy Minds: Advancing Wellbeing, Leadership, and Lasting Impact",
  },
  {
    id: 8,
    title: "Signature Global Transformation Conference",
    date: "October 08-09, 2026",
    location: "Melbourne, Australia",
    city: "Melbourne",
    country: "Australia",
    category: "business",
    imageKey: "home_img_8",
    description:
      "The Signature Global Transformation Conference is a forward-thinking international platform designed to inspire leaders, innovators, and professionals to drive meaningful change in a rapidly evolving world. Bringing together global experts, entrepreneurs, and changemakers, the conference focuses on transformational leadership, innovation, and sustainable growth across industries.\n\nThrough powerful keynote sessions, expert-led panels, and interactive discussions, the event explores key areas such as digital transformation, strategic thinking, change management, and future-ready leadership. Attendees will gain practical insights, tools, and strategies to navigate change, lead with agility, and create lasting impact within their organizations and communities.\n\nThe conference also fosters collaboration and global networking, providing a dynamic space to exchange ideas, build partnerships, and explore new opportunities. It empowers participants to transform vision into action and contribute to a more innovative, inclusive, and future-ready world.",
    themes: [
      "Transformational Leadership & Change Management",
      "Innovation & Disruptive Technologies",
      "Strategic Thinking & Future-Ready Leadership",
      "Digital Transformation & AI in Business",
      "Emotional Intelligence & Adaptive Leadership",
      "Organizational Transformation & Culture Change",
      "Entrepreneurship & Business Transformation",
      "Leadership in Times of Uncertainty",
      "Personal Growth & Leadership Transformation",
      "Resilience & Agility in Leadership",
      "Sustainable Development & Global Impact",
      "Diversity, Equity & Inclusive Transformation",
      "Leadership Communication & Influence",
      "Coaching, Mentorship & Leadership Development",
      "High-Performance Leadership Strategies",
      "Data-Driven Decision Making",
      "Social Innovation & Community Transformation",
      "Workforce Transformation & Future Skills",
      "Building Agile & Innovative Organizations",
    ],
    fullDescription:
      "Theme: Transforming Vision into Impact: Leadership, Innovation, and Global Change",
  },
];

/*-----------------------------EUROPE DATA--------------------------------------------*/
// ============================================================
//  EURO SUMMITS — EUROPE REGION
//  Format matches existing conferenceSeed structure
//  region: "europe" added to all entries
//  imageKey: placeholder keys — swap with actual keys later
// ============================================================

const euroSummits = [
  {
    id: "eu-summit-01",
    title: "Euro Innovara Women in AI, STEM & Leadership Summit",
    date: "September 09–12, 2026",
    location: "Berlin, Germany",
    city: "Berlin",
    country: "Germany",
    region: "europe",
    category: "ai-stem",
    imageKey: "euro_innovara",
    description:
      "The Euro Innovara Women in AI, STEM & Leadership Summit is a powerful platform dedicated to empowering women in technology and leadership roles. Hosted in Berlin, this summit celebrates diversity, innovation, and inclusion.\n\nIt provides a space where women can share their journeys, overcome challenges, and inspire others to pursue careers in STEM and leadership. The conference emphasizes representation and equal opportunities.\n\nSessions will explore AI innovation, leadership growth, and breaking barriers in tech industries. Participants will engage in meaningful discussions and collaborative learning.\n\nAttendees will leave empowered, confident, and inspired to lead the future of innovation.",
    themes: [
      "Women in AI & Emerging Technologies",
      "STEM Leadership & Career Development",
      "Breaking Barriers in Tech Industries",
      "Diversity & Inclusion in Technology",
      "AI Innovation & Future Applications",
      "Women Pioneers in Science & Engineering",
      "Digital Transformation & Leadership",
      "Ethical AI & Responsible Technology",
      "Representation & Equal Opportunities in STEM",
      "Entrepreneurship in Tech & Innovation",
      "Leadership Skills for Women in Technology",
      "Mentorship & Sponsorship in STEM Careers",
      "Overcoming Gender Bias in Tech",
      "Future of Work & AI Integration",
      "Building Inclusive Tech Organizations",
      "STEM Education & Inspiring the Next Generation",
      "Data Science, Machine Learning & Women Leaders",
      "Collaborative Innovation & Cross-Industry Impact",
      "Personal Branding & Visibility in Tech",
      "Global Impact Through Technology & Leadership",
    ],
    fullDescription:
      "Theme: Empowering Women to Lead the Future of AI, STEM & Innovation",
  },
  {
    id: "eu-summit-02",
    title: "Euro NeuroRise Future Wellness & Human Performance Summit",
    date: "September 09–12, 2026",
    location: "Berlin, Germany",
    city: "Berlin",
    country: "Germany",
    region: "europe",
    category: "wellness",
    imageKey: "euro_neurorise",
    description:
      "The Euro NeuroRise Summit focuses on unlocking human potential through wellness, neuroscience, and performance strategies. Hosted in Berlin, it brings together experts and leaders in human optimization.\n\nThis summit explores how mental, physical, and emotional well-being contribute to high performance. It redefines success as balance and alignment.\n\nParticipants will learn about resilience, biohacking, and peak performance strategies.\n\nAttendees will leave with tools to enhance their energy, mindset, and productivity while maintaining well-being.",
    themes: [
      "Neuroscience of Human Performance",
      "Biohacking & Peak Performance Strategies",
      "Mental Wellness & Cognitive Optimization",
      "Physical Health & High-Performance Living",
      "Emotional Well-Being & Resilience",
      "Mindfulness & Mind-Body Connection",
      "Sleep, Recovery & Energy Management",
      "Stress Resilience & Nervous System Regulation",
      "Nutrition, Movement & Brain Health",
      "Flow States & Deep Focus",
      "Hormonal Health & Performance",
      "Breathwork & Somatic Practices",
      "High-Performance Habits & Routines",
      "Leadership Wellness & Sustainable Success",
      "Technology & Tools for Human Optimization",
      "Psychology of Motivation & Behaviour Change",
      "Redefining Success: Balance & Alignment",
      "Burnout Prevention & Long-Term Vitality",
      "Integrative Health Approaches for Leaders",
      "Future of Wellness & Human Potential",
    ],
    fullDescription:
      "Theme: Unlocking Human Potential: Wellness, Neuroscience, and Peak Performance",
  },
  {
    id: "eu-summit-03",
    title: "Euro Aurelia Women Leadership & Global Impact Summit",
    date: "October 21–24, 2026",
    location: "Rome, Italy",
    city: "Rome",
    country: "Italy",
    region: "europe",
    category: "women-leadership",
    imageKey: "euro_aurelia",
    description:
      "The Euro Aurelia Summit is a global gathering of women leaders committed to creating meaningful change. Hosted in Rome, it focuses on purpose-driven leadership.\n\nThis conference provides a platform for women to inspire, collaborate, and lead with impact. It emphasizes compassion, vision, and empowerment.\n\nParticipants will explore global leadership, social impact, and transformation.\n\nAttendees will leave inspired to lead with intention and create lasting change.",
    themes: [
      "Purpose-Driven Women's Leadership",
      "Creating Meaningful Global Impact",
      "Compassionate Leadership & Vision",
      "Women as Agents of Change",
      "Social Impact & Community Transformation",
      "Empowerment Through Collaboration",
      "Global Leadership & Cross-Cultural Influence",
      "Leadership with Intention & Integrity",
      "Advocacy, Voice & Visibility for Women",
      "Inspiring the Next Generation of Women Leaders",
      "Sustainability & Responsible Leadership",
      "Inclusive Leadership & Global Equity",
      "Entrepreneurship & Social Innovation",
      "Legacy Building & Long-Term Impact",
      "Women in Policy, Diplomacy & Governance",
      "Storytelling as a Tool for Leadership",
      "Resilience & Courage in Leadership",
      "Mentorship, Sponsorship & Leadership Pipelines",
      "Networking & Building Global Alliances",
      "Transformational Leadership & the Future of Impact",
    ],
    fullDescription:
      "Theme: Lead with Purpose, Create Lasting Change: Women's Leadership and Global Impact",
  },
  {
    id: "eu-summit-04",
    title: "Euro Serenza Mind & Leadership Wellness Summit",
    date: "October 21–24, 2026",
    location: "Rome, Italy",
    city: "Rome",
    country: "Italy",
    region: "europe",
    category: "wellness",
    imageKey: "euro_serenza",
    description:
      "The Euro Serenza Summit is designed for leaders seeking balance, clarity, and inner strength. Hosted in Rome, it focuses on mental wellness and leadership.\n\nThis summit provides a space to recharge, reflect, and reconnect with purpose. It highlights mindfulness and emotional resilience.\n\nParticipants will gain tools for stress management and conscious leadership.\n\nAttendees will leave with calm, clarity, and renewed energy to lead effectively.",
    themes: [
      "Mental Wellness & Conscious Leadership",
      "Mindfulness Practices for Leaders",
      "Emotional Resilience & Inner Strength",
      "Stress Management & Calm Leadership",
      "Balance, Clarity & Purpose in Leadership",
      "Self-Awareness & Reflective Leadership",
      "Recharging & Preventing Leadership Burnout",
      "Mindful Decision-Making & Focus",
      "Inner Work & Outer Leadership",
      "Breath, Body & Mind Integration",
      "Emotional Intelligence for Effective Leadership",
      "Creating Space for Reflection & Growth",
      "Psychological Well-Being in High-Pressure Roles",
      "Sustainable Leadership Through Inner Balance",
      "Values-Driven Leadership & Authenticity",
      "Presence, Attention & Mindful Communication",
      "Reconnecting with Purpose & Meaning",
      "Nature, Stillness & Leadership Renewal",
      "Holistic Wellness as a Leadership Foundation",
      "Transforming Pressure into Performance with Mindfulness",
    ],
    fullDescription:
      "Theme: Lead from Within: Balance, Clarity, and Mindful Leadership for Lasting Impact",
  },
  {
    id: "eu-summit-05",
    title: "Euro Lumina Women Leadership & Influence Summit",
    date: "March 04–08, 2027",
    location: "Paris, France",
    city: "Paris",
    country: "France",
    region: "europe",
    category: "women-leadership",
    imageKey: "euro_lumina",
    description:
      "The Euro Lumina Women Leadership & Influence Summit is a transformative global gathering dedicated to empowering women to rise as influential leaders in today's evolving world. Hosted in Paris, this summit brings together visionary women, entrepreneurs, professionals, and changemakers committed to creating meaningful impact.\n\nThis conference goes beyond traditional leadership—it focuses on influence, confidence, and authenticity. It provides a platform for women to share journeys, amplify voices, and inspire others through real stories.\n\nParticipants will explore leadership development, empowerment, and breaking barriers through sessions and networking.\n\nAttendees will leave with renewed confidence, clarity, and purpose, ready to lead with impact.",
    themes: [
      "Women's Leadership & Authentic Influence",
      "Confidence Building & Self-Empowerment",
      "Authenticity as a Leadership Superpower",
      "Amplifying Women's Voices & Stories",
      "Breaking Barriers & Glass Ceilings",
      "Personal Brand & Thought Leadership",
      "Influence, Persuasion & Communication",
      "Visionary Leadership & Future Thinking",
      "Entrepreneurship & Women-Led Ventures",
      "Navigating Power Dynamics as a Woman Leader",
      "Mentorship & Building Women Leadership Pipelines",
      "Diversity, Equity & Inclusive Influence",
      "Leadership Presence & Executive Communication",
      "Overcoming Imposter Syndrome & Self-Doubt",
      "Social Media & Digital Influence for Women",
      "Courage, Risk-Taking & Bold Leadership",
      "Purpose-Driven Leadership & Inner Clarity",
      "Collaboration & Building Powerful Networks",
      "Women in Business, Politics & Global Change",
      "Future of Women's Leadership & Global Influence",
    ],
    fullDescription:
      "Theme: Rise, Influence, Lead: Empowering Women to Shape the Future with Confidence and Purpose",
  },
  {
    id: "eu-summit-06",
    title: "Euro Mindscape Leadership & Wellness Summit",
    date: "March 04–08, 2027",
    location: "Paris, France",
    city: "Paris",
    country: "France",
    region: "europe",
    category: "wellness",
    imageKey: "euro_mindscape",
    description:
      "The Euro Mindscape Leadership & Wellness Summit is a unique platform that brings together leadership and well-being, emphasizing that true leadership begins from within. Set in Paris, this summit is designed for individuals who seek to lead with clarity, balance, and emotional strength.\n\nIn a world where leaders face constant pressure and rapid change, this conference creates a space to pause, reflect, and reconnect with mental and emotional well-being. It highlights the importance of resilience, mindfulness, and self-awareness as key components of effective leadership.\n\nParticipants will engage in sessions covering emotional intelligence, stress management, mindfulness practices, and sustainable success strategies. The summit encourages leaders to align their inner well-being with their external achievements.\n\nAttendees will gain practical tools to enhance both personal and professional growth. More importantly, they will leave with a refreshed mindset—ready to lead with purpose, compassion, and confidence.",
    themes: [
      "Leadership Begins from Within",
      "Emotional Intelligence & Self-Awareness",
      "Mindfulness & Presence in Leadership",
      "Stress Management & Mental Clarity",
      "Resilience as a Core Leadership Skill",
      "Sustainable Success & Inner Alignment",
      "Work-Life Integration & Balance",
      "Conscious Leadership & Values",
      "Mental Health & High-Performance Leadership",
      "Burnout Prevention & Energy Renewal",
      "Purposeful Leadership & Inner Motivation",
      "Emotional Strength & Vulnerable Leadership",
      "Mindful Communication & Deep Listening",
      "Personal Growth & Leadership Transformation",
      "Psychological Safety & Team Well-Being",
      "Breathwork, Movement & Leadership Vitality",
      "Self-Compassion & Authentic Leadership",
      "Aligning Inner Well-Being with Outer Achievements",
      "Creating Wellness-First Organizational Cultures",
      "Future of Compassionate & Conscious Leadership",
    ],
    fullDescription:
      "Theme: True Leadership Begins Within: Clarity, Balance, and Emotional Strength for Sustainable Impact",
  },
  {
    id: "eu-summit-07",
    title: "Euro Nexora AI & STEM Summit",
    date: "June 03–06, 2027",
    location: "London, UK",
    city: "London",
    country: "United Kingdom",
    region: "europe",
    category: "ai-stem",
    imageKey: "euro_nexora_stem",
    description:
      "The Euro Nexora AI & STEM Summit is a forward-looking conference designed to bring together innovators, researchers, and leaders shaping the future of technology. Hosted in London, this summit explores how artificial intelligence and STEM advancements can drive meaningful global impact.\n\nAs technology continues to transform industries, this conference provides a platform for knowledge sharing, innovation, and collaboration. It emphasizes not only technological growth but also ethical responsibility and human-centered innovation.\n\nParticipants will explore AI trends, digital transformation, future careers, and inclusive innovation. The summit encourages diverse voices to contribute to the evolving technological landscape.\n\nAttendees will gain valuable insights, connect with experts, and explore opportunities to lead in the future of innovation. This is not just about technology—it's about shaping a smarter and more responsible world.",
    themes: [
      "Artificial Intelligence & Future Applications",
      "STEM Innovation & Research Frontiers",
      "Ethical AI & Responsible Technology",
      "Human-Centered Innovation & Design Thinking",
      "Digital Transformation Across Industries",
      "Machine Learning & Data Science Advances",
      "Inclusive Innovation & Diversity in Tech",
      "AI in Healthcare, Education & Sustainability",
      "Future Careers in AI & STEM",
      "Robotics, Automation & the Future of Work",
      "Climate Technology & Green Innovation",
      "Cybersecurity & Digital Safety",
      "Women & Underrepresented Groups in STEM",
      "Tech Entrepreneurship & Startup Ecosystems",
      "Global Collaboration in Science & Technology",
      "AI Policy, Governance & Regulation",
      "Quantum Computing & Next-Gen Technologies",
      "Knowledge Sharing & Open Innovation",
      "STEM Education & Building Future Talent",
      "Shaping a Smarter, More Responsible World",
    ],
    fullDescription:
      "Theme: Innovation with Purpose: Shaping a Smarter and More Responsible World Through AI & STEM",
  },
  {
    id: "eu-summit-08",
    title: "Euro Nexora Strategic Leadership & Business Summit",
    date: "June 03–06, 2027",
    location: "London, UK",
    city: "London",
    country: "United Kingdom",
    region: "europe",
    category: "business",
    imageKey: "euro_nexora_business",
    description:
      "The Euro Nexora Strategic Leadership & Business Summit is designed for forward-thinking leaders and entrepreneurs who are shaping the future of business. Held in London, this summit focuses on strategy, innovation, and leadership excellence.\n\nIn today's competitive landscape, success requires more than knowledge—it requires vision, adaptability, and strategic thinking. This conference provides a platform for professionals to exchange ideas, learn from experts, and develop future-ready strategies.\n\nSessions will cover leadership in uncertainty, business growth, innovation, and decision-making. Participants will gain insights into navigating challenges and leading with confidence.\n\nAttendees will leave with practical strategies, valuable connections, and a stronger leadership mindset. This summit empowers individuals to lead with clarity, purpose, and long-term vision.",
    themes: [
      "Strategic Leadership & Business Excellence",
      "Visionary Thinking & Long-Term Strategy",
      "Innovation & Competitive Advantage",
      "Leadership in Times of Uncertainty",
      "Entrepreneurship & Business Growth",
      "Decision-Making & Strategic Problem Solving",
      "Organizational Leadership & Culture",
      "Digital Transformation & Business Strategy",
      "Financial Intelligence & Business Acumen",
      "Leading High-Performance Teams",
      "Agile Leadership & Adaptability",
      "Global Business Trends & Market Insights",
      "Mergers, Acquisitions & Scaling Strategy",
      "Stakeholder Management & Influence",
      "Sustainability & Responsible Business",
      "Women in Business Leadership",
      "Networking, Partnerships & Strategic Alliances",
      "Future of Work & Workforce Strategy",
      "Personal Leadership & Executive Presence",
      "Building Future-Ready Organizations",
    ],
    fullDescription:
      "Theme: Lead with Vision, Grow with Strategy: Shaping the Future of Business and Leadership",
  },
];

/*-----------------------NORTH AMERICA DATA-----------------------------*/

const northAmericaConferences = [
  {
    id: "na-01",
    title: "EmpoweringHer Signature Global Conference: Women Redefining Power",
    date: "October 05–06, 2026",
    location: "Toronto, Canada",
    city: "Toronto",
    country: "Canada",
    region: "north-america",
    category: "women-leadership",
    imageKey: "na_empoweringher",
    description:
      "The EmpoweringHer Signature Global Conference: Women Redefining Power is a bold and transformative platform dedicated to celebrating and elevating women who are rewriting the rules of leadership and influence. Hosted in Toronto, this conference brings together trailblazing women leaders, entrepreneurs, changemakers, and visionaries from across the globe.\n\nThis conference challenges traditional notions of power and invites women to step boldly into their strength, voice, and vision. Through powerful keynote sessions, expert-led panels, and dynamic discussions, participants will explore what it truly means to lead with confidence, authenticity, and purpose.\n\nAttendees will gain actionable tools, build meaningful connections, and leave inspired to redefine power on their own terms — creating lasting impact in their organizations, communities, and the world.",
    themes: [
      "Women Redefining Power & Leadership",
      "Authentic Leadership & Personal Power",
      "Breaking Barriers & Challenging the Status Quo",
      "Confidence, Courage & Bold Decision-Making",
      "Women's Voice, Visibility & Influence",
      "Emotional Intelligence & Empowered Leadership",
      "Fearless Leadership in a Changing World",
      "Purpose-Driven Leadership & Legacy Building",
      "Resilience & Inner Strength in Leadership",
      "Entrepreneurship & Women-Led Innovation",
      "Overcoming Imposter Syndrome & Self-Doubt",
      "Inclusive Leadership & Workplace Equity",
      "Mentorship, Sponsorship & Women Lifting Women",
      "Mental Strength & Psychological Empowerment",
      "Mindful Leadership & Self-Awareness",
      "Navigating Power Dynamics as a Woman",
      "Work-Life Integration & Sustainable Leadership",
      "Diversity, Equity & Inclusion in Leadership",
      "Global Impact Through Women's Leadership",
      "The Future of Women's Power & Influence",
    ],
    fullDescription:
      "Theme: Redefining Power: Women Leading with Boldness, Authenticity, and Global Impact",
  },
  {
    id: "na-02",
    title:
      "She Rises Within Signature Global Conference: From Vision to Legacy",
    date: "October 05–06, 2026",
    location: "Toronto, Canada",
    city: "Toronto",
    country: "Canada",
    region: "north-america",
    category: "women-leadership",
    imageKey: "na_sherises",
    description:
      "The She Rises Within Signature Global Conference: From Vision to Legacy is a deeply transformative gathering for women who are ready to turn their inner vision into an enduring legacy. Hosted in Toronto, this conference brings together women leaders, entrepreneurs, coaches, and changemakers committed to living and leading with intention.\n\nThis conference explores the journey from inner clarity to outward impact — empowering women to align their purpose with action and build legacies that outlast titles and positions. Through inspiring keynotes, reflective workshops, and powerful networking, participants will deepen their self-leadership, sharpen their vision, and take bold steps toward creating lasting change.\n\nAttendees will leave with renewed clarity, a stronger sense of identity, and the strategic tools needed to rise, lead, and leave a legacy worth remembering.",
    themes: [
      "From Inner Vision to Outer Legacy",
      "Self-Leadership & Personal Transformation",
      "Purpose-Driven Leadership & Meaning",
      "Legacy Building & Long-Term Impact",
      "Rising Through Adversity & Challenge",
      "Mindful Leadership & Inner Clarity",
      "Visionary Thinking & Strategic Planning",
      "Emotional Resilience & Inner Power",
      "Women's Identity, Voice & Authentic Leadership",
      "Confidence, Growth Mindset & Limitless Potential",
      "Entrepreneurship & Vision-Led Business",
      "Mentorship & Creating Ripple Effects of Impact",
      "Healing, Growth & Leadership Reinvention",
      "Courage to Lead & Rise Beyond Fear",
      "Empowered Women Empowering Others",
      "Work-Life Balance & Sustainable Success",
      "Diversity & Inclusion in Legacy Leadership",
      "Community Building & Collective Rise",
      "Storytelling, Influence & Thought Leadership",
      "The Future of Women's Leadership & Legacy",
    ],
    fullDescription:
      "Theme: She Rises Within: Aligning Vision, Purpose, and Legacy for Transformational Leadership",
  },
  {
    id: "na-03",
    title: "Resilient Woman Signature Mental Health & Leadership",
    date: "October 05–06, 2026",
    location: "Toronto, Canada",
    city: "Toronto",
    country: "Canada",
    region: "north-america",
    category: "wellness",
    imageKey: "na_resilientwoman",
    description:
      "The Resilient Woman Signature Mental Health & Leadership Conference is a powerful and compassionate platform dedicated to advancing the mental health and leadership resilience of women across all walks of life. Hosted in Toronto, this conference unites women leaders, mental health professionals, coaches, and advocates in a shared commitment to well-being and sustainable leadership.\n\nThis conference explores the critical relationship between mental health and effective leadership, addressing the unique challenges women face in high-pressure environments. Through expert-led sessions, open conversations, and practical workshops, participants will gain tools to manage stress, overcome burnout, build emotional resilience, and lead with clarity and confidence.\n\nAttendees will leave feeling seen, supported, and equipped — with a renewed commitment to prioritizing their mental health as the foundation of their greatest leadership.",
    themes: [
      "Women's Mental Health & Leadership Resilience",
      "Emotional Intelligence & Self-Regulation",
      "Stress Management & Burnout Prevention",
      "Building Psychological Resilience in Women",
      "Mindful Leadership & Mental Clarity",
      "Trauma-Informed Leadership & Recovery",
      "Overcoming Anxiety, Self-Doubt & Imposter Syndrome",
      "Mental Strength & Inner Power",
      "Psychological Safety in the Workplace",
      "Self-Care as a Leadership Non-Negotiable",
      "Holistic Wellness: Mind, Body & Spirit",
      "Work-Life Balance & Sustainable Success",
      "Healing, Growth & Personal Transformation",
      "Neuroscience of Resilience & Mental Performance",
      "Coaching & Mentorship for Mental Wellbeing",
      "Courageous Women Leading Through Adversity",
      "Energy Management & Mental Productivity",
      "Creating Mentally Healthy Work Cultures",
      "Purpose, Meaning & Inner Alignment",
      "The Future of Women's Mental Health in Leadership",
    ],
    fullDescription:
      "Theme: Resilient Minds, Empowered Leaders: Advancing Women's Mental Health and Leadership Strength",
  },
];

// ─────────────────────────────────────────────────────────────
//  REGION: MIDDLE EAST
//  Dubai, UAE · November 23–24, 2026
// ─────────────────────────────────────────────────────────────

const middleEastConferences = [
  {
    id: "me-01",
    title: "The Rise of Unstoppable Women Signature Global Conference",
    date: "November 23–24, 2026",
    location: "Dubai, UAE",
    city: "Dubai",
    country: "United Arab Emirates",
    region: "middle-east",
    category: "women-leadership",
    imageKey: "me_unstoppablewomen",
    description:
      "The Rise of Unstoppable Women Signature Global Conference is an electrifying international platform that celebrates and amplifies the power of women who refuse to be limited. Hosted in Dubai, this conference brings together bold women leaders, entrepreneurs, innovators, and changemakers from across the globe to share their stories, strategies, and strength.\n\nThis conference is built for women who are breaking through every barrier — personal, professional, and societal — and rising unstoppably toward their highest potential. Through high-energy keynotes, expert panels, and transformative discussions, participants will ignite their fearless leadership, sharpen their mindset, and step boldly into their power.\n\nAttendees will leave fired up, connected, and unstoppable — ready to lead without limits, inspire others, and make their mark on the world.",
    themes: [
      "Unstoppable Women & Fearless Leadership",
      "Breaking Through Barriers & Limitations",
      "Bold Mindset & Limitless Potential",
      "Resilient Leadership Under Pressure",
      "Women's Power, Voice & Global Influence",
      "Courageous Leadership & Risk-Taking",
      "Rising Through Adversity & Setbacks",
      "Entrepreneurship & Unstoppable Vision",
      "Mental Strength & Psychological Grit",
      "Empowered Women Changing the World",
      "Confidence, Identity & Self-Belief",
      "Fearless Leadership in Male-Dominated Industries",
      "Purpose-Driven Leadership & Inner Drive",
      "Emotional Intelligence & Adaptive Strength",
      "Mentorship & Women Supporting Women",
      "Diversity, Equity & Inclusion in Leadership",
      "Growth Mindset & Continuous Reinvention",
      "Work-Life Integration & Sustainable Drive",
      "Global Women's Leadership & Cross-Cultural Impact",
      "The Future of Unstoppable Women's Leadership",
    ],
    fullDescription:
      "Theme: Unstoppable: Women Rising Beyond Limits to Lead, Inspire, and Transform the World",
  },
  {
    id: "me-02",
    title: "Global Women's Empowerment & Leadership Signature Forum Conference",
    date: "November 23–24, 2026",
    location: "Dubai, UAE",
    city: "Dubai",
    country: "United Arab Emirates",
    region: "middle-east",
    category: "women-leadership",
    imageKey: "me_globalempowerment",
    description:
      "The Global Women's Empowerment & Leadership Signature Forum Conference is a premier international platform dedicated to advancing women's empowerment and leadership on a global scale. Hosted in Dubai, this forum brings together women executives, policymakers, entrepreneurs, thought leaders, and advocates united by a shared vision of gender equity and transformational leadership.\n\nThis conference serves as a powerful forum for exchange, collaboration, and action — exploring the strategies, systems, and stories that drive meaningful women's empowerment across industries, cultures, and borders. Through keynote addresses, expert-led panels, and roundtable discussions, participants will engage with the most pressing issues facing women in leadership today.\n\nAttendees will leave with expanded perspectives, powerful global connections, and a renewed commitment to driving empowerment within their spheres of influence.",
    themes: [
      "Global Women's Empowerment & Leadership",
      "Gender Equity & Equal Opportunity in Leadership",
      "Women in Policy, Governance & Global Affairs",
      "Inclusive Leadership & Systemic Change",
      "Entrepreneurship & Economic Empowerment of Women",
      "Cross-Cultural Leadership & Global Collaboration",
      "Women's Rights, Advocacy & Social Justice",
      "Empowering Women in Emerging Markets",
      "Leadership Development & Women's Pipelines",
      "Mental Strength & Empowered Mindset",
      "Purposeful Leadership & Social Impact",
      "Resilience, Courage & Rising Through Challenges",
      "Education, Mentorship & Women Lifting Women",
      "Digital Empowerment & Women in Technology",
      "Financial Independence & Wealth Building for Women",
      "Community Leadership & Grassroots Empowerment",
      "Diversity, Equity & Belonging in Organizations",
      "Health, Wellbeing & Empowered Living",
      "Storytelling & Amplifying Women's Voices",
      "The Future of Global Women's Empowerment",
    ],
    fullDescription:
      "Theme: Empowered Women, Empowered World: Leading with Purpose, Equity, and Global Vision",
  },
  {
    id: "me-03",
    title: "Global Women Changemakers Signature Summit",
    date: "November 23–24, 2026",
    location: "Dubai, UAE",
    city: "Dubai",
    country: "United Arab Emirates",
    region: "middle-east",
    category: "women-leadership",
    imageKey: "me_changemakers",
    description:
      "The Global Women Changemakers Signature Summit is a dynamic international gathering celebrating women who are driving meaningful change in their communities, industries, and the world. Hosted in Dubai, this summit brings together women innovators, social entrepreneurs, activists, leaders, and visionaries committed to making a difference.\n\nThis summit shines a spotlight on changemakers — women who challenge the norm, champion equity, and inspire transformation at every level. Through compelling keynotes, impact-focused panels, and collaborative workshops, participants will explore how women are leading change across sectors including technology, education, health, policy, and social enterprise.\n\nAttendees will leave inspired, connected to a global network of changemakers, and equipped with fresh strategies to amplify their impact and accelerate meaningful change.",
    themes: [
      "Women as Agents of Change & Transformation",
      "Social Innovation & Impact Leadership",
      "Changemaking Through Entrepreneurship",
      "Community Leadership & Grassroots Impact",
      "Women in Technology & Digital Change",
      "Education, Health & Social Sector Leadership",
      "Advocacy, Activism & Policy Change",
      "Sustainability & Environmental Changemaking",
      "Bold Leadership & Courageous Action",
      "Purpose-Driven Leadership & Mission Impact",
      "Empowered Women Changing Systems",
      "Global Collaboration & Partnership for Change",
      "Rising Leaders & Next-Gen Changemakers",
      "Storytelling as a Vehicle for Change",
      "Resilience, Grit & Leading Through Opposition",
      "Innovation, Creativity & Disruptive Thinking",
      "Diversity, Inclusion & Equity in Change",
      "Mind Mastery & Inner Drive for Impact",
      "Building Movements & Collective Leadership",
      "The Future of Women-Led Global Change",
    ],
    fullDescription:
      "Theme: Women Leading Change: Innovation, Impact, and a Better World for All",
  },
  {
    id: "me-04",
    title: "She Leads with Strength Signature Global Conference",
    date: "November 23–24, 2026",
    location: "Dubai, UAE",
    city: "Dubai",
    country: "United Arab Emirates",
    region: "middle-east",
    category: "women-leadership",
    imageKey: "me_leadswithstrength",
    description:
      "The She Leads with Strength Signature Global Conference is a powerful and inspiring platform dedicated to celebrating women who lead with resilience, conviction, and authentic strength. Hosted in Dubai, this conference brings together women leaders, executives, coaches, and emerging leaders from around the world to explore what it means to lead powerfully from the inside out.\n\nThis conference goes beyond surface-level leadership — it delves into the mental, emotional, and strategic dimensions of strength-based leadership. Through transformational keynotes, candid conversations, and practical workshops, participants will develop the inner fortitude and outer strategy needed to lead boldly in any environment.\n\nAttendees will leave empowered with a deeper sense of strength, a clearer leadership identity, and the confidence to lead with impact, grace, and unwavering conviction.",
    themes: [
      "Strength-Based Leadership for Women",
      "Inner Power & Emotional Fortitude",
      "Resilient Leadership Under Pressure",
      "Confident Leadership & Executive Presence",
      "Mental Strength & Psychological Toughness",
      "Fearless Leadership & Bold Decision-Making",
      "Authentic Strength & Leadership Identity",
      "Purposeful Leadership & Values-Driven Action",
      "Balanced Leadership & Sustainable Strength",
      "Empowered Women Leading with Conviction",
      "Mindful Leadership & Emotional Intelligence",
      "Rising Leaders & Building Leadership Strength",
      "Courageous Women & Leading Through Adversity",
      "Growth Mindset & Continuous Leadership Growth",
      "Self-Leadership & Personal Mastery",
      "Mentorship, Coaching & Developing Strong Leaders",
      "Women's Voice, Influence & Leadership Impact",
      "Thriving Forward: Energy, Focus & Productivity",
      "Inclusive Leadership & Strength in Diversity",
      "The Future of Strength-Led Women's Leadership",
    ],
    fullDescription:
      "Theme: She Leads with Strength: Resilience, Conviction, and the Power to Lead from Within",
  },
];

export default euroSummits;

export const conferences = conferenceSeed.map((conference) => ({
  ...conference,
  image: eventImages[conference.imageKey],
}));

export const categoryFilters = [
  { id: "all", label: "All Conferences" },
  { id: "women-leadership", label: "Women Leadership" },
  { id: "wellness", label: "Wellness" },
  { id: "business", label: "Business" },
];
